openapi: 3.0.3
info:
  title: API Sistema SOA - Gestión de Créditos
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  # --- ENDPOINTS EXISTENTES ---

  /credito/productos:
    get:
      tags:
        - Catalogos
      summary: Listar productos crediticios
      operationId: listarProductos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductoDTO'

  /credito/recurrencias:
    get:
      tags:
        - Catalogos
      summary: Listar tipos de recurrencia
      operationId: listarRecurrencias
      responses:
        '200':
          description: Lista de recurrencias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecurrenciaDTO'

  /credito/riesgos:
    get:
      tags:
        - Catalogos
      summary: Listar niveles de riesgo
      operationId: listarRiesgos
      responses:
        '200':
          description: Lista de riesgos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RiesgoDTO'

  /credito/periodos:
    get:
      tags:
        - Catalogos
      summary: Listar periodos
      operationId: listarPeriodos
      responses:
        '200':
          description: Lista de periodos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PeriodoDTO'

  /credito/solicitar:
    post:
      tags:
        - Credito
      summary: Registrar solicitud
      operationId: registrarSolicitud
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolicitudCreditoDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolicitudCreditoDTO'

  # --- NUEVOS ENDPOINTS DE DOCUMENTOS ---

  /credito/documentos/subir:
    post:
      tags:
        - Documentos
      summary: Subir documento físico al servidor y registrar en BD
      operationId: subirDocumento
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                archivo:
                  type: string
                  format: binary
                codExpediente:
                  type: integer
                tipoDoc:
                  type: string
                  description: 'Clave del tipo de documento (ej: dni, ficha, visita)'
      responses:
        '200':
          description: Documento guardado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentoExpedienteDTO'

  /credito/documentos/ver/{filename}:
    get:
      tags:
        - Documentos
      summary: Descargar o visualizar un documento por nombre
      operationId: verDocumento
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Archivo binario (PDF, JPG, etc.)
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

components:
  schemas:
    # --- DTOs INDIVIDUALES ---
    ProductoDTO:
      type: object
      properties:
        codProducto:
          type: integer
        nombre:
          type: string

    RecurrenciaDTO:
      type: object
      properties:
        codRecurrencia:
          type: integer
        nombre:
          type: string

    RiesgoDTO:
      type: object
      properties:
        codRiesgo:
          type: integer
        descripcion:
          type: string

    PeriodoDTO:
      type: object
      properties:
        codPeriodo:
          type: integer
        descripcion:
          type: string

    SolicitudCreditoDTO:
      type: object
      properties:
        dniSocio:
          type: string
        montoSolicitado:
          type: number
        codProducto:
          type: integer
        codRecurrencia:
          type: integer
        codRiesgo:
          type: integer
        codPeriodo:
          type: integer
        actividad:
          type: string
        codTrabajador:
          type: integer

    # --- NUEVO DTO DE DOCUMENTO ---
    DocumentoExpedienteDTO:
      type: object
      description: Respuesta al subir un documento
      properties:
        codDocumento:
          type: integer
        nombreArchivo:
          type: string
        fechaCarga:
          type: string
          format: date-time
        codExpediente:
          type: integer
        tipoDetectado:
          type: string
          description: 'Campo calculado para indicar si es dni, ficha, etc.'